onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider DUT
add wave -noupdate /tb_video_stream_to_window/DUT/clk_i
add wave -noupdate /tb_video_stream_to_window/DUT/rst_i
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_i
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_val_i
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_i
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_i
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_i
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_i
add wave -noupdate /tb_video_stream_to_window/DUT/win_data_o
add wave -noupdate /tb_video_stream_to_window/DUT/win_data_val_o
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_o
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_o
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_o
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_o
add wave -noupdate /tb_video_stream_to_window/DUT/push_data
add wave -noupdate /tb_video_stream_to_window/DUT/active_wr_buf
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_val_masked
add wave -noupdate /tb_video_stream_to_window/DUT/active_rd_buf
add wave -noupdate /tb_video_stream_to_window/DUT/inact_pos
add wave -noupdate /tb_video_stream_to_window/DUT/read_buf
add wave -noupdate /tb_video_stream_to_window/DUT/read_ready
add wave -noupdate /tb_video_stream_to_window/DUT/data_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_data_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/data_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_data_val_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_line_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_line_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_frame_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_frame_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/unread_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_unread_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/unread_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/unread_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/read_done
add wave -noupdate /tb_video_stream_to_window/DUT/data_shift_reg_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/act_data_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_shift_reg_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/act_data_val_reg
add wave -noupdate /tb_video_stream_to_window/DUT/valid_output
add wave -noupdate /tb_video_stream_to_window/DUT/valid_output_d1
add wave -noupdate -divider {Line Buffer 0}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/clk_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/rst_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/px_data_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/px_data_val_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/pop_line_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/px_data_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/px_data_val_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/empty_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/unread_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/wr_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_size}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/rd_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/read_in_progress}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_end_valid}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/push_data}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/empty}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/was_sof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/was_eof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/line_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/frame_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/px_data_val}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[0]/line_buf/unread}
add wave -noupdate -divider {Line Buffer 1}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/clk_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/rst_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/px_data_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/px_data_val_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/pop_line_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/px_data_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/px_data_val_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/empty_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/unread_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/wr_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_size}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/rd_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/read_in_progress}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_end_valid}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/push_data}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/empty}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/was_sof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/was_eof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/line_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/frame_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/px_data_val}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[1]/line_buf/unread}
add wave -noupdate -divider {Line Buffer 2}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/clk_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/rst_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/px_data_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/px_data_val_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/pop_line_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/px_data_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/px_data_val_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/empty_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/unread_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/wr_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_size}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/rd_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/read_in_progress}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_end_valid}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/push_data}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/empty}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/was_sof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/was_eof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/line_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/frame_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/px_data_val}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[2]/line_buf/unread}
add wave -noupdate -divider {Line Buffer 3}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/clk_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/rst_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/px_data_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/px_data_val_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_start_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_end_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/pop_line_i}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/px_data_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/px_data_val_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_start_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_end_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/empty_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/unread_o}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/wr_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_size}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/rd_ptr}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/read_in_progress}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_end_valid}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/push_data}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/empty}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/was_sof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/was_eof}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/line_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_start}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/frame_end}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/px_data_val}
add wave -noupdate {/tb_video_stream_to_window/DUT/line_buffers[3]/line_buf/unread}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {21609406 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 544
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {133180282 ps}
