onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_video_stream_to_window/DUT/clk_i
add wave -noupdate /tb_video_stream_to_window/DUT/rst_i
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_i
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_val_i
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_i
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_i
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_i
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_i
add wave -noupdate /tb_video_stream_to_window/DUT/win_data_o
add wave -noupdate /tb_video_stream_to_window/DUT/win_data_val_o
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_o
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_o
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_o
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_o
add wave -noupdate /tb_video_stream_to_window/DUT/push_data
add wave -noupdate /tb_video_stream_to_window/DUT/push_data_d1
add wave -noupdate /tb_video_stream_to_window/DUT/active_wr_buf
add wave -noupdate /tb_video_stream_to_window/DUT/px_data_val_masked
add wave -noupdate /tb_video_stream_to_window/DUT/active_rd_buf
add wave -noupdate /tb_video_stream_to_window/DUT/read_buf
add wave -noupdate /tb_video_stream_to_window/DUT/data_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_data_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/data_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_data_val_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_line_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_line_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_frame_start_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_frame_end_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/unread_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/shifted_unread_from_buf
add wave -noupdate /tb_video_stream_to_window/DUT/unread_to_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_start_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/line_end_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_start_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/frame_end_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/unread_shift_reg
add wave -noupdate /tb_video_stream_to_window/DUT/shift
add wave -noupdate /tb_video_stream_to_window/DUT/read_done
add wave -noupdate /tb_video_stream_to_window/DUT/data_shift_reg_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/act_data_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_shift_reg_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/act_data_val_reg
add wave -noupdate /tb_video_stream_to_window/DUT/data_from_buf_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/data_val_from_buf_unpacked
add wave -noupdate /tb_video_stream_to_window/DUT/read_ready
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1289538950 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 428
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {7066254086 ps}
